export 'package:real_estate/view/login.dart';
export 'package:real_estate/view/forget_pass.dart';
export 'package:real_estate/view/opt.dart';
export 'package:real_estate/view/home.dart';
export 'package:real_estate/view/register.dart';
export 'package:real_estate/view/property_details.dart';
export 'package:real_estate/view/user_info_screen.dart' hide main;
export 'package:real_estate/view/bottom_navigation_wrapper.dart';
export 'package:real_estate/view/mortgage_cal.dart' hide main;
export 'package:real_estate/view/user_profile_screen.dart' hide main;
